apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alfred.fullname" . }}
  labels:
    {{ include "alfred.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{ include "alfred.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ template "alfred.name" . }}
        release: {{ .Release.Name }}
        {{ include "alfred.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          {{- range $name, $value := .Values.env }}
          {{- if not (empty $value) }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.env.PORT }}
              protocol: TCP
